# Generated by Django 5.1.5 on 2025-02-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('order_type', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('remarks', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
