# Generated by Django 5.1.5 on 2025-02-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
