# Generated by Django 5.1.5 on 2025-01-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
