# Generated by Django 5.1.5 on 2025-02-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_aboutus_aboutusimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='aboutusimage',
            options={'verbose_name_plural': 'About Us Images'},
        ),
    ]
