# Generated by Django 5.1.5 on 2025-02-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_alter_aboutus_options_alter_aboutusimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='slug',
            field=models.SlugField(default='a', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
