# Generated by Django 5.1.5 on 2025-02-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_aboutus_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
