# Generated by Django 5.1.5 on 2025-02-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_aboutus_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='name',
            field=models.CharField(default='about us', max_length=100),
        ),
    ]
