# Generated by Django 5.1.5 on 2025-02-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_aboutus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='slug',
        ),
    ]
