# Generated by Django 5.1.5 on 2025-01-22 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_category_tooth_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooth',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bucket.toothmodel'),
        ),
    ]
