# Generated by Django 5.1.5 on 2025-02-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_tooth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooth',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
