# Generated by Django 5.1.5 on 2025-02-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_category_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='language',
        ),
        migrations.AddField(
            model_name='tooth',
            name='language',
            field=models.CharField(default='en', max_length=255),
        ),
    ]
