# Generated by Django 5.1.5 on 2025-02-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0003_remove_category_language_tooth_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(default='en', max_length=255),
        ),
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(default='en', max_length=255),
        ),
    ]
