# Generated by Django 5.1.5 on 2025-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0003_alter_tooth_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255), max_length=255, unique=True),
        ),
    ]
