# Generated by Django 5.1.5 on 2025-02-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0004_category_language_series_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='language',
        ),
        migrations.RemoveField(
            model_name='series',
            name='language',
        ),
    ]
