# Generated by Django 5.1.5 on 2025-01-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0004_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='slug_url',
        ),
    ]
