# Generated by Django 5.1.5 on 2025-01-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0007_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
