# Generated by Django 5.1.5 on 2025-01-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0009_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooth',
            name='image_src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
