# Generated by Django 5.1.5 on 2025-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_category_tooth_category'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='nav',
            field=models.ManyToManyField(blank=True, related_name='navs', to='bucket.tooth'),
        ),
    ]
